/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControllerFornecedor;
import controller.ControllerProdutos;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelFornecedor;
import model.ModelProdutos;
import util.DataClasses;
import util.TabelaRenderer;

/**
 * @author  BLSoft
 * www.Blsoft.com.br
 * Venda de software e código fonte
 */
public class ViewProduto extends javax.swing.JFrame {

    ModelProdutos modelProdutos = new ModelProdutos();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ArrayList<ModelProdutos> listamModelProdutos = new ArrayList<ModelProdutos>();
    ArrayList<ModelFornecedor> listaFornecedor = new ArrayList<ModelFornecedor>();
    String tipoCadastro;
    int linha, ultimanota;
    DefaultTableModel modelo;
    boolean lista_minimo = false;
    
    
    /**
     * Creates new form ViewProduto
     */
    public ViewProduto() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        setLocationRelativeTo(null);
        
        TableCellRenderer renderer = new TabelaRenderer();
        tbProdutos.setDefaultRenderer(Object.class, renderer);
                
        modelo = (DefaultTableModel) tbProdutos.getModel();
        
        this.carregarProdutos();
        this.listarFornecedor();
        this.desabilitarCampos();
        ButtonGroup group = new ButtonGroup();
        group.add(radio_codigo);
        group.add(radio_nome);
        
/**     UIManager.put("TabbedPane.selected", new Color(230, 216, 174));
        jTabbedPane1.updateUI();
  */      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btPesquisaProduto = new javax.swing.JButton();
        tfPesquisaProduto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbFornecedores = new componentes.UJComboBox();
        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfEstoque = new javax.swing.JFormattedTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        lbl_lucroreal = new javax.swing.JLabel();
        lbl_lucro = new javax.swing.JLabel();
        txt_porcentagem = new javax.swing.JFormattedTextField();
        lbl_lucro1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vl_custo = new util.CampoDinheiro();
        tfValor = new util.CampoDinheiro();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        txtminimo = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        radio_codigo = new javax.swing.JRadioButton();
        radio_nome = new javax.swing.JRadioButton();
        btnminimo = new javax.swing.JButton();
        btnentrada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setMinimumSize(new java.awt.Dimension(150, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(227, 227, 227));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setMaximumSize(null);
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentResized(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(240, 240, 240));
        jLayeredPane1.setOpaque(true);

        btPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Search.png"))); // NOI18N
        btPesquisaProduto.setText("Pesquisar");
        btPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaProdutoActionPerformed(evt);
            }
        });
        btPesquisaProduto.setBounds(380, 180, 120, 30);
        jLayeredPane1.add(btPesquisaProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tfPesquisaProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaProdutoActionPerformed(evt);
            }
        });
        tfPesquisaProduto.setBounds(20, 180, 270, 30);
        jLayeredPane1.add(tfPesquisaProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setInheritsPopupMenu(true);
        jScrollPane2.setMinimumSize(null);

        tbProdutos.setAutoCreateRowSorter(true);
        tbProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Valor", "Estoque", "Estoque Minimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbProdutos.setIntercellSpacing(new java.awt.Dimension(4, 4));
        tbProdutos.setMaximumSize(new java.awt.Dimension(2147483647, 0));
        tbProdutos.setMinimumSize(new java.awt.Dimension(360, 0));
        tbProdutos.setRowHeight(30);
        tbProdutos.setShowHorizontalLines(false);
        tbProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbProdutos);

        jScrollPane2.setBounds(20, 220, 860, 360);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Add.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        btNovo.setBounds(410, 590, 100, 27);
        jLayeredPane1.add(btNovo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Modify.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        btAlterar.setBounds(290, 590, 110, 27);
        jLayeredPane1.add(btAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Delete.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        btExcluir.setBounds(160, 590, 110, 27);
        jLayeredPane1.add(btExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/No.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        btCancelar.setBounds(20, 590, 130, 27);
        jLayeredPane1.add(btCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Save.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(770, 590, 110, 27);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Fornecedor:");
        jLabel3.setBounds(140, 60, 70, 15);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cbFornecedores.setDoubleBuffered(true);
        cbFornecedores.setBounds(140, 80, 310, 20);
        jLayeredPane1.add(cbFornecedores, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");
        jLabel1.setBounds(190, 10, 70, 15);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tfCodigo.setEditable(false);
        tfCodigo.setBounds(20, 30, 150, 20);
        jLayeredPane1.add(tfCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Código:");
        jLabel5.setBounds(20, 10, 110, 15);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jtfNome.setBounds(190, 30, 259, 20);
        jLayeredPane1.add(jtfNome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Estoque mínimo:");
        jLabel4.setBounds(20, 110, 110, 15);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tfEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        tfEstoque.setBounds(20, 80, 50, 20);
        jLayeredPane1.add(tfEstoque, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane3.setOpaque(true);

        lbl_lucroreal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_lucroreal.setForeground(new java.awt.Color(255, 255, 153));
        lbl_lucroreal.setBounds(120, 50, 90, 20);
        jLayeredPane3.add(lbl_lucroreal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_lucro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_lucro.setText("%");
        lbl_lucro.setBounds(50, 50, 30, 17);
        jLayeredPane3.add(lbl_lucro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_porcentagem.setEditable(false);
        txt_porcentagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_porcentagemKeyReleased(evt);
            }
        });
        txt_porcentagem.setBounds(0, 50, 50, 20);
        jLayeredPane3.add(txt_porcentagem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbl_lucro1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_lucro1.setText("Porc. de lucro");
        lbl_lucro1.setBounds(0, 30, 100, 17);
        jLayeredPane3.add(lbl_lucro1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Lucro em moeda");
        jLabel7.setBounds(120, 30, 110, 15);
        jLayeredPane3.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vl_custo.setBounds(0, 0, 80, 20);
        jLayeredPane3.add(vl_custo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tfValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfValorKeyReleased(evt);
            }
        });
        tfValor.setBounds(120, 0, 80, 20);
        jLayeredPane3.add(tfValor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(460, 30, 233, 80);
        jLayeredPane1.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Valor de custo:");
        jLabel6.setToolTipText("");
        jLabel6.setBounds(460, 10, 90, 15);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Valor de venda:");
        jLabel2.setBounds(580, 10, 86, 15);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UN", "CX", "LT", "KG", "GR" }));
        jComboBox1.setBounds(70, 80, 60, 20);
        jLayeredPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtminimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        txtminimo.setBounds(20, 130, 50, 20);
        jLayeredPane1.add(txtminimo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Estoque:");
        jLabel8.setBounds(20, 60, 49, 15);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radio_codigo.setText("Código");
        radio_codigo.setBounds(300, 170, 70, 23);
        jLayeredPane1.add(radio_codigo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        radio_nome.setText("Nome");
        radio_nome.setBounds(300, 190, 60, 23);
        jLayeredPane1.add(radio_nome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnminimo.setText("abaixo do mínimo");
        btnminimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimoActionPerformed(evt);
            }
        });
        btnminimo.setBounds(510, 180, 150, 30);
        jLayeredPane1.add(btnminimo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnentrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Up.png"))); // NOI18N
        btnentrada.setText("Entrada no estoque");
        btnentrada.setActionCommand("entrada");
        btnentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentradaActionPerformed(evt);
            }
        });
        btnentrada.setBounds(520, 590, 200, 27);
        jLayeredPane1.add(btnentrada, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Cadastro de produto", jLayeredPane1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
     
        this.vincularTamanhoTab();

    }//GEN-LAST:event_formComponentResized

    private void jTabbedPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentResized
        this.vincularTamanhoTab();

    }//GEN-LAST:event_jTabbedPane1ComponentResized

    private void btnentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentradaActionPerformed

        btAlterarActionPerformed(evt);

        if(this.linha > -1){
            ViewEntradaEstoque estoque = new ViewEntradaEstoque(modelProdutos);
            estoque.setVisible(true);
        }
    }//GEN-LAST:event_btnentradaActionPerformed

    private void btnminimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimoActionPerformed

        lista_minimo=true;
        listamModelProdutos = controllerProdutos.getEstoqueMinimo();
        DefaultTableModel modelo = (DefaultTableModel) tbProdutos.getModel();
        TableCellRenderer renderer = new TabelaRenderer();
        tbProdutos.setDefaultRenderer(Object.class, renderer);
        tbProdutos.getColumnModel().getColumn(0).setCellRenderer(renderer);

        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listamModelProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{

                listamModelProdutos.get(i).getCodigo(),
                listamModelProdutos.get(i).getNome(),
                listamModelProdutos.get(i).getValor(),
                listamModelProdutos.get(i).getEstoque(),
                listamModelProdutos.get(i).getEstoqueMinimo()
            });
        }

    }//GEN-LAST:event_btnminimoActionPerformed

    private void txt_porcentagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_porcentagemKeyReleased
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(!vl_custo.getText().isEmpty()){
                float custo = DataClasses.converterMoedaParaFloat(vl_custo.getText());
                float margem = DataClasses.converterMoedaParaFloat(txt_porcentagem.getText());
                float valor = (custo/100) * margem;
                float valor_venda = custo+valor;
                this.tfValor.setText(String.format("%.2f",custo+valor));
                float lucro = valor_venda - custo;
                this.lbl_lucroreal.setText("R$ "+ String.format("%.2f",lucro)  );
            }
        }
        //this.txt_porcentagem.setText(String.format("%.2f", porc)+"%");
    }//GEN-LAST:event_txt_porcentagemKeyReleased
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tipoCadastro.equals("novo")){
            salvarProduto();
        } else if(tipoCadastro.equals("alteracao")){
            alterarProduto();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.desabilitarCampos();
        this.tipoCadastro="";
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirProduto();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        this.linha = this.tbProdutos.getSelectedRow();
        if(this.linha > -1){
            novoProduto();
            habilitarCampos();
            recuperarProduto();
            tipoCadastro = "alteracao";
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        novoProduto();
        habilitarCampos();
        tipoCadastro = "novo";
    }//GEN-LAST:event_btNovoActionPerformed

    private void tfPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaProdutoActionPerformed

        System.out.print( evt.getActionCommand() );
        btPesquisaProdutoActionPerformed(evt);

    }//GEN-LAST:event_tfPesquisaProdutoActionPerformed

    private void btPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaProdutoActionPerformed

        if(lista_minimo){
            carregarProdutos();
        }
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);
        this.tbProdutos.setRowSorter(sorter);
        String text = tfPesquisaProduto.getText();
        int campo = radio_nome.isSelected() ? 1 : 0;
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text, campo));
    }//GEN-LAST:event_btPesquisaProdutoActionPerformed

    private void tfValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorKeyReleased
        
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(!vl_custo.getText().isEmpty()){

                float custo = DataClasses.converterMoedaParaFloat(vl_custo.getText());
                float venda = DataClasses.converterMoedaParaFloat(tfValor.getText());
                float lucro = venda - custo;
                float porc = (lucro/custo) * 100;

                this.lbl_lucroreal.setText("R$ "+ String.format("%.2f",lucro)  );
                this.txt_porcentagem.setText(String.format("%.2f", porc));
            }
        }
        
    }//GEN-LAST:event_tfValorKeyReleased

    private void listarFornecedor(){
        listaFornecedor = controllerFornecedor.getListaFornecedorController();
        cbFornecedores.removeAllItems();
        for (int i = 0; i < listaFornecedor.size(); i++){
            cbFornecedores.addItem(listaFornecedor.get(i).getNome());
        }
    }
    
    private void excluirProduto(){
        int linha = tbProdutos.getSelectedRow();
        String nome = (String) tbProdutos.getValueAt(linha, 1);
        int codigo = (int) tbProdutos.getValueAt(linha, 0);
        //pegunta se realmente deseja excluir
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja"
                + " excluir o registro:\n" + "\n " + nome + "?", "Atenção", JOptionPane.YES_NO_OPTION);
        //se sim exclui, se não não faz nada    
        if (opcao == JOptionPane.OK_OPTION) {
            if (controllerProdutos.excluirProdutosController(codigo)) {
                JOptionPane.showMessageDialog(null, "Registro excluido com suscesso!");
                carregarProdutos();
            }else{
            JOptionPane.showMessageDialog(this, "Erro ao e os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private boolean recuperarProduto() {
     
        String codigo = (String) tbProdutos.getValueAt(linha, 0);
        try {
            //recupera os dados do banco
            modelProdutos = controllerProdutos.getProdutosController(codigo);
            //seta os dados na interface
            this.tfCodigo.setText(String.valueOf(modelProdutos.getCodigo()));
            this.jtfNome.setText(modelProdutos.getNome());
            this.tfValor.setText(DataClasses.converterFloatParaMoeda(modelProdutos.getValor(), false) );
            this.tfEstoque.setText(String.valueOf(modelProdutos.getEstoque()));
            this.cbFornecedores.setSelectedItem(controllerFornecedor.getFornecedorController(modelProdutos.getFornecedoresCodigo()).getNome());
            this.vl_custo.setText(DataClasses.converterFloatParaMoeda(modelProdutos.getValorCusto(), false) ) ;
            this.txtminimo.setText( modelProdutos.getEstoqueMinimo().toString() );
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }        
    }
    
    private boolean alterarProduto(){
        modelProdutos.setCodigo( this.tfCodigo.getText() );
        modelProdutos.setNome(this.jtfNome.getText());
        modelProdutos.setValor(DataClasses.converterMoedaParaFloat(this.tfValor.getText()));
        modelProdutos.setFornecedoresCodigo(controllerFornecedor.getFornecedorController(this.cbFornecedores.getSelectedItem().toString()).getCodigo());
        modelProdutos.setEstoque(Integer.parseInt(this.tfEstoque.getText()));
        modelProdutos.setEstoqueMinimo(Integer.parseInt(this.txtminimo.getText()));
        int id = listamModelProdutos.get(this.linha).getId();
        modelProdutos.setId(id);
        //salvar 
        if (controllerProdutos.atualizarProdutosController(modelProdutos)) {
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
            this.desabilitarCampos();
            this.carregarProdutos();
            this.tipoCadastro="";
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void carregarProdutos() {
        this.linha = -1;
        lista_minimo=false;
        listamModelProdutos = controllerProdutos.getListaProdutosController();
        //tbProdutos.setSelectionBackground(new Color(223,255,216));
        
        modelo.setNumRows(0);
        //CARREGA OS DADOS DA LISTA NA TABELA
        int cont = listamModelProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                
                listamModelProdutos.get(i).getCodigo(),
                listamModelProdutos.get(i).getNome(),
                listamModelProdutos.get(i).getValor(),
                listamModelProdutos.get(i).getEstoque(),
                listamModelProdutos.get(i).getEstoqueMinimo()
                //listamModelProdutos.get(i).getEstoqueMinimo()                 
            });
        }
    }
    
    protected void desabilitarCampos(){
        this.limparCampos();
        jtfNome.setEditable(false);       
        tfValor.setEditable(false);
        vl_custo.setEditable(false);
        tfEstoque.setEditable(false);
        tfCodigo.setEditable(false);
        cbFornecedores.setEditable(false);                
        //tfPesquisaProduto.setEditable(false);
        txt_porcentagem.setEditable(false);
        txtminimo.setEditable(false);
        lbl_lucroreal.setText("");
        carregarProdutos();
    }
    
    protected void limparCampos(){
        jtfNome.setText("");
        tfValor.setText("");
        vl_custo.setText("");
        tfEstoque.setText("");
        tfCodigo.setText("");
        txt_porcentagem.setText("");
        txtminimo.setText("");
    }
    
    private void novoProduto(){
        habilitarCampos();
        tfCodigo.setText("");
        jtfNome.setText("");
        tfValor.setText("");
        vl_custo.setText("");
        tfEstoque.setText("");
        cbFornecedores.setSelectedItem("");
        txtminimo.setText("");
        tipoCadastro = "novo";
    }
    
    private void habilitarCampos(){
        jtfNome.setEditable(true);
        tfCodigo.setEditable(true);
        tfValor.setEditable(true);
        tfEstoque.setEditable(true);
        vl_custo.setEditable(true);
        txt_porcentagem.setEditable(true);
        txtminimo.setEditable(true);
    }
    
    private boolean salvarProduto(){
        modelProdutos.setCodigo( this.tfCodigo.getText() );
        modelProdutos.setNome(this.jtfNome.getText());
        modelProdutos.setValor(DataClasses.converterMoedaParaFloat(this.tfValor.getText()));
        modelProdutos.setFornecedoresCodigo(controllerFornecedor.getFornecedorController(this.cbFornecedores.getSelectedItem().toString()).getCodigo());
        modelProdutos.setEstoque(Integer.parseInt(this.tfEstoque.getText()));
        modelProdutos.setValorCusto(DataClasses.converterMoedaParaFloat(this.vl_custo.getText()));
        modelProdutos.setEstoqueMinimo( Integer.parseInt(this.txtminimo.getText()) );
        //salvar 
        if (controllerProdutos.salvarProdutosController(modelProdutos)>0) {
            JOptionPane.showMessageDialog(this, "Registro gravado com sucesso!");
            this.desabilitarCampos();
            this.carregarProdutos();
            this.tipoCadastro="";
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar os dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void vincularTamanhoTab(){
        int altura = getHeight()-40;
        int largura = getWidth()-10;
        jTabbedPane1.setSize(largura, altura);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisaProduto;
    private javax.swing.JButton btnentrada;
    private javax.swing.JButton btnminimo;
    private componentes.UJComboBox cbFornecedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JLabel lbl_lucro;
    private javax.swing.JLabel lbl_lucro1;
    private javax.swing.JLabel lbl_lucroreal;
    private javax.swing.JRadioButton radio_codigo;
    private javax.swing.JRadioButton radio_nome;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JFormattedTextField tfEstoque;
    private javax.swing.JTextField tfPesquisaProduto;
    private util.CampoDinheiro tfValor;
    private javax.swing.JFormattedTextField txt_porcentagem;
    private javax.swing.JFormattedTextField txtminimo;
    private util.CampoDinheiro vl_custo;
    // End of variables declaration//GEN-END:variables
}
